name: Publish to Maven Central
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    
    - name: Verify GPG setup
      run: gpg --list-secret-keys --keyid-format LONG
    
    - name: Publish to Maven Central
      run: |
        ./mvnw deploy -B \
        -Prelease \
        -DskipTests
      env:
        # Maven Central credentials via https://central.sonatype.com/account
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}